spring.profiles.active: dev

logging.level.io.summerframework: trace

better-error-pages:
  archive-timeout: 300000 # 5min
  # Following is optional, it's resolved from BetterErrorPagesDemoApplication class
  # however giving this property improves startup performance significantly but won't affect runtime performance.
  package-name: com.example